language: node_js

node_js:
   - "stable"

install:
   - npm install

services:
   - postgresql

env:
  global:
     - CC_TEST_REPORTER_ID=3a583cf0d38ca19f23ddce92853ba43474a361ce106f3ef7b316fd5296d9ec58

before_script:
   - psql -c 'create database cohort_application_test_db;' -U postgres

script:
   - npm run start-test

after_success:
   - npm run coverage